# Data preprocessing using pandas and scikit-learn

### Feature selection

Data preprocessing is most always the step before training a machine learning model. There are features that are not very useful for predicting a given outcome. For example, including an `id` field which uniquely identifies each sample does not make much sense. 
Thus, such variables can be safely deleted.


In [108]:
import pandas as pd
from matplotlib import pyplot as plt
filename="../../additional_resources/datasets/NYC Squirrels/data.csv"
df = pd.read_csv(filename)
df.columns

Index(['X', 'Y', 'Unique Squirrel ID', 'Hectare', 'Shift', 'Date',
       'Hectare Squirrel Number', 'Age', 'Primary Fur Color',
       'Highlight Fur Color', 'Combination of Primary and Highlight Color',
       'Color notes', 'Location', 'Above Ground Sighter Measurement',
       'Specific Location', 'Running', 'Chasing', 'Climbing', 'Eating',
       'Foraging', 'Other Activities', 'Kuks', 'Quaas', 'Moans', 'Tail flags',
       'Tail twitches', 'Approaches', 'Indifferent', 'Runs from',
       'Other Interactions', 'Lat/Long'],
      dtype='object')

Again, we'll ask you do to a bit of work yourself. This time, we ask you to drop unnecessary columns.

In [109]:
# Drop the `Unique Squirrel ID'` column
df = df.drop("Unique Squirrel ID",axis =1)
df.columns


Index(['X', 'Y', 'Hectare', 'Shift', 'Date', 'Hectare Squirrel Number', 'Age',
       'Primary Fur Color', 'Highlight Fur Color',
       'Combination of Primary and Highlight Color', 'Color notes', 'Location',
       'Above Ground Sighter Measurement', 'Specific Location', 'Running',
       'Chasing', 'Climbing', 'Eating', 'Foraging', 'Other Activities', 'Kuks',
       'Quaas', 'Moans', 'Tail flags', 'Tail twitches', 'Approaches',
       'Indifferent', 'Runs from', 'Other Interactions', 'Lat/Long'],
      dtype='object')

### Feature slicing
Feature slicing is the act of *slicing* a feature into multiple different features.
For example, we can slice the `Date` into day, month, and year.


In [110]:
df['Date'].head()

0    10142018
1    10062018
2    10102018
3    10182018
4    10182018
Name: Date, dtype: int64

Hint: use the `Series.apply()` method with a lambda function. [[Help]](https://www.analyticsvidhya.com/blog/2020/03/what-are-lambda-functions-in-python/)


In [111]:
s = df["Date"].squeeze()
s

0       10142018
1       10062018
2       10102018
3       10182018
4       10182018
          ...   
3018    10072018
3019    10132018
3020    10122018
3021    10102018
3022    10122018
Name: Date, Length: 3023, dtype: int64

In [112]:
s = df["Date"].squeeze()
#a= s.apply(lambda x: 'date'= x,'day':x[:
day = s.apply(lambda x: str(x)[0:2])
month = s.apply(lambda x:str(x)[2:4])
year = s.apply(lambda x:str(x)[4:])
df['day']= day
df['month'] =month
df['year'] = year

df[['day','month','year']].head()

day month  year
0  10    14  2018
1  10    06  2018
2  10    10  2018
3  10    18  2018
4  10    18  2018

### Feature engineering

You can create new features based on the features you have. These might be more useful for your (future) machine learning model than the ones that are already present in the dataset.
In this squirrel dataset, most of the fields encode the action taken by the squirrel when being approached by the human.
We will combine them into a single feature `Reaction` with values `'yes'` and `'no'`.

In [113]:
df.head()

X          Y Hectare Shift      Date  Hectare Squirrel Number  \
0 -73.956134  40.794082     37F    PM  10142018                        3   
1 -73.957044  40.794851     37E    PM  10062018                        3   
2 -73.976831  40.766718     02E    AM  10102018                        3   
3 -73.975725  40.769703     05D    PM  10182018                        5   
4 -73.959313  40.797533     39B    AM  10182018                        1   

        Age Primary Fur Color Highlight Fur Color  \
0       NaN               NaN                 NaN   
1     Adult              Gray            Cinnamon   
2     Adult          Cinnamon                 NaN   
3  Juvenile              Gray                 NaN   
4       NaN               NaN                 NaN   

  Combination of Primary and Highlight Color  ... Tail flags Tail twitches  \
0                                          +  ...      False         False   
1                              Gray+Cinnamon  ...      False         False   
2                                  Cinnamon+  ...      False         False   
3                                      Gray+  ...      False         False   
4                                          +  ...      False         False   

  Approaches Indifferent  Runs from  Other Interactions  \
0      False       False      False                 NaN   
1      False       False       True                  me   
2      False        True      False                 NaN   
3      False       False       True                 NaN   
4      False       False      False                 NaN   

                                       Lat/Long  day  month  year  
0    POINT (-73.9561344937861 40.7940823884086)   10     14  2018  
1  POINT (-73.9570437717691 40.794850940803904)   10     06  2018  
2   POINT (-73.9768311751004 40.76671780725581)   10     10  2018  
3    POINT (-73.9757249834141 40.7697032606755)   10     18  2018  
4     POINT (-73.9593126695714 40.797533370163)   10     18  2018  

[5 rows x 33 columns]

In [114]:
reaction_columns = ['Kuks', 'Quaas', 'Moans', 'Tail flags',
                   'Tail twitches', 'Approaches', 'Runs from',
                   'Other Interactions']

df['Reaction'] = df[reaction_columns].any(axis=1)
df['Reaction'] = df['Reaction'].apply(lambda x : "yes" if x else "no")
df['Reaction']

0        no
1       yes
2        no
3       yes
4       yes
       ... 
3018    yes
3019     no
3020     no
3021     no
3022    yes
Name: Reaction, Length: 3023, dtype: object

A important step for a data processing pipeline is making the data understandable for machine learning algorithms. Most of them do not understand strings, like `yes` and `no` in our newly created column.
We need to transform them to a binary format so that the machine learning model can take advantage of that feature.We are going to **One Hot Encode** our feature.


In [115]:
pd.get_dummies(df.Reaction, prefix='Reaction')

Reaction_no  Reaction_yes
0               1             0
1               0             1
2               1             0
3               0             1
4               0             1
...           ...           ...
3018            0             1
3019            1             0
3020            1             0
3021            1             0
3022            0             1

[3023 rows x 2 columns]

However, we have a redundancy here, as we could just transform `'yes'` to `1` and `'no'` to `0` in our `Reaction` column. This can be done by setting the argument `drop_first` to `True`.

In [116]:
df = pd.get_dummies(df.Reaction, prefix='Reaction', drop_first="True")
df.rename(columns={"Reaction_yes" : "Reaction"})

Reaction
0            0
1            1
2            0
3            1
4            1
...        ...
3018         1
3019         0
3020         0
3021         0
3022         1

[3023 rows x 1 columns]


Similar things can be done after converting the data frame to an array using the `scikit-learn` library with `LabelBinarizer` or `OneHotEncoder`.

## Feature normalization or standardization
Although they are sometimes used interchangeably, normalization and standardization are two different ways to bring a column of values to a common scale.
In this section, we're going to use the word normalization to refer to this concept.

Why do we normalize data ?

*For example, assume your input dataset contains one column with values ranging from 0 to 1, and another column with values ranging from 10,000 to 100,000. The great difference in the scale of the numbers could cause problems when you attempt to combine the values as features during modeling.* [[Source]](https://docs.microsoft.com/en-us/azure/machine-learning/studio-module-reference/normalize-data)

Some algorithms require that data be normalized before training a model. Other algorithms perform their own data scaling or normalization.

Given a column of values *x*, if we choose to scale them, there are a few options:

- Normalization, also called *min-max scaling*, rescales every value to a range between [0, 1]. The maximum and the minimum are computed for each column separately.

  $$ z = \frac{x - min(x)}{max(x) - min(x)} $$

- Standardization, also called z-score normalization, rescales the value around a 0 mean and a standard deviation of 1. It essentially transforms all values of *x* to a *z-score*. Mean and standard deviation are computed for each column separately.

$$ z = \frac{x - mean(x)}{std(x)} $$


### Be careful!

When you want to normalize your dataset, you have to do so **AFTER** splitting your data into different train-test splits. Indeed, normalizing your data before would use some information from your testing set in the training set, thus biasing the model.
Indeed, in a real world scenario, you would not have access to the testing set, as this would be the data that you are meant to predict.

The procedure is the following:
1. Split your data into train and test
2. For every variable $x$ of your **training set**, compute $max(x_{train})$ and $min(x_{train})$ , or $mean(x_{train})$ and $std(x_{train})$ depending if you do min-max scaling or z-score-normalization.
3. Normalize your training set and your testing set using these values (here I'm only showing the testing set).
$$ z_{test} = \frac{x_{test} - min(x_{train})}{max(x_{train}) - min(x_{train})} $$


$$ z_{test} = \frac{x_{test} - mean(x_{train})}{std(x_{train})} $$


In [117]:
from sklearn.model_selection import train_test_split
from sklearn import datasets
import numpy as np
dataset = datasets.load_breast_cancer()
X, y = dataset.data, dataset.target

In [118]:
print(dataset.feature_names)


['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [119]:
print(type(dataset))
print(type(X))
print(X)
print(y)

<class 'sklearn.utils.Bunch'>
<class 'numpy.ndarray'>
[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 

In [120]:
print(dataset.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [121]:
print(dataset)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [122]:
# Splitting data into train and test split
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=41, test_size=0.2)
print(X_train.shape)


(455, 30)


In [123]:
print(X_train)

[[1.283e+01 1.573e+01 8.289e+01 ... 9.783e-02 3.006e-01 7.802e-02]
 [1.426e+01 1.817e+01 9.122e+01 ... 7.530e-02 2.636e-01 7.676e-02]
 [1.365e+01 1.316e+01 8.788e+01 ... 8.056e-02 2.380e-01 8.718e-02]
 ...
 [1.375e+01 2.377e+01 8.854e+01 ... 6.106e-02 2.663e-01 6.321e-02]
 [2.016e+01 1.966e+01 1.311e+02 ... 1.425e-01 3.055e-01 5.933e-02]
 [1.145e+01 2.097e+01 7.381e+01 ... 6.127e-02 2.762e-01 8.851e-02]]


In [124]:
#X_train[0].sum()/len(X_train[0])
len(X_train[0])
len(X_train)

455

Here, we'll want you to use numpy's mean and standard deviation functions to standardize each feature of the training and testing set. These are `np.mean()` and `np.std()`.

In [126]:
# Standardizing each feature using the train mean and standard deviation

for idx, name in enumerate(dataset.feature_names):
    # Get mean and standard deviation from training set (per feature)
    
     mean=np.mean(X_train[:,idx])
     stdev = np.std(X_train[:,idx])
     

     print(f"Feature '{name}' has mean {mean:.2f} and standard deviation {stdev:.2f}")
    # Standardize training and testing set using the mean and standard deviation from the training set
     z = (X_train[:,idx] -mean)/stdev
     z_test =(X_test[:,idx]-mean)/stdev
    
     X_train[:,idx] = z
     X_test[:,idx]= z_test
#print(X_train)
print(X_test)


Feature 'mean radius' has mean -0.00 and standard deviation 1.00
Feature 'mean texture' has mean 0.00 and standard deviation 1.00
Feature 'mean perimeter' has mean -0.00 and standard deviation 1.00
Feature 'mean area' has mean -0.00 and standard deviation 1.00
Feature 'mean smoothness' has mean -0.00 and standard deviation 1.00
Feature 'mean compactness' has mean 0.00 and standard deviation 1.00
Feature 'mean concavity' has mean -0.00 and standard deviation 1.00
Feature 'mean concave points' has mean -0.00 and standard deviation 1.00
Feature 'mean symmetry' has mean 0.00 and standard deviation 1.00
Feature 'mean fractal dimension' has mean 0.00 and standard deviation 1.00
Feature 'radius error' has mean -0.00 and standard deviation 1.00
Feature 'texture error' has mean -0.00 and standard deviation 1.00
Feature 'perimeter error' has mean -0.00 and standard deviation 1.00
Feature 'area error' has mean 0.00 and standard deviation 1.00
Feature 'smoothness error' has mean -0.00 and standard

If you run the previous cell twice (without running the others cells again), you'll see that the second time, the mean and standard deviation for each feature will be 0 and 1 respectively, which is exactly what we want when we standardize (z-score normalization).

## Resampling

Sometimes, when you have multiple classes and the number of samples of each class are not equally distributed, i.e. there is an imbalance in the number of samples of each class, you can resort to resampling.
Resampling is using more (or less) of a given class to get a balanced dataset.

**BE CAREFUL**, resample **AFTER** splitting your data set into two parts. You do not want to accidentally have a copy of a testing sample in the training set.
Moreover, **do not resample the testing set**. This would give a false sense of the performance of the model.


In [127]:

import sklearn
import numpy as np
from sklearn import datasets

dataset = datasets.load_breast_cancer()
X, y = dataset.data, dataset.target


In [129]:
# We separate the samples of the different classes
class_one_idx = np.argwhere(y==1)
class_zero_idx = np.argwhere(y==0)

class_one_x = np.squeeze(X[class_one_idx])
class_zero_x = np.squeeze(X[class_zero_idx])

print("Shape of class 0 samples : ", class_zero_x.shape)
print("Shape of class 1 samples : ", class_one_x.shape)


Shape of class 0 samples :  (212, 30)
Shape of class 1 samples :  (357, 30)


You see that we have 212 samples of class 0 and 357 samples of class 1.
We can either upsample, i.e. take more samples of, the minority class (here class 0) or we can downsample, i.e. take fewer samples of, the majority class (here class 1).
To do this, we first have to separate the samples of each class.

In [130]:
from sklearn.utils import resample

# Upsample minority class
class_zero_upsampled = resample(class_zero_x, 
                                 replace=True,     # sample with replacement
                                 n_samples=357,    # to match majority class
                                 random_state=123) # reproducible results

print("New shape of class 0 samples: ",class_zero_upsampled.shape)

# Downsample majority class
class_one_downsampled = resample(class_one_x, 
                                 replace=True,     # sample with replacement
                                 n_samples=212,    # to match minority class
                                 random_state=123) # reproducible results

print("New shape of class 1 samples: ",class_one_downsampled.shape)


New shape of class 0 samples:  (357, 30)
New shape of class 1 samples:  (212, 30)


After having either upsampled our minority class, or downsampled our majority class, we can combine the upsampled with the majority class or the downsampled with the minority class to have a balanced data set.

Which one you use depends on what you want to do, and which one does best.

In [131]:
X_balanced = np.concatenate((class_zero_upsampled, class_one_x), axis=0)
print("(Upsampled) Balanced data set shape : ", X_balanced.shape)

X_balanced = np.concatenate((class_one_downsampled, class_zero_x), axis=0)
print("(Downsampled) Balanced data set shape : ", X_balanced.shape)

(Upsampled) Balanced data set shape :  (714, 30)
(Downsampled) Balanced data set shape :  (424, 30)


## Reading material and additional ressources

[[1] Feature Engineering - Elite Data Science](https://elitedatascience.com/feature-engineering)  
[[2] Feature Engineering - Towards Data Science](https://towardsdatascience.com/feature-engineering-for-machine-learning-3a5e293a5114)  
[[3] Feature Engineering Tutorial - Kaggle](https://towardsdatascience.com/feature-engineering-for-machine-learning-3a5e293a5114)  
[[4] LabelBinarizer - scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html)  
[[5] OneHotEncoder - scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html)  
[[6] Zscore - Simply Psychology](https://www.simplypsychology.org/z-score.html)  
[[7] Normalize data - Microsoft Azure](https://docs.microsoft.com/en-us/azure/machine-learning/studio-module-reference/normalize-data)  
[[8] How to handle imbalanced classes - Elite Data Science ](https://elitedatascience.com/imbalanced-classes)